Styling
mrkamin/Bookstore-2nd-Project pull request #5
Opened 2023-03-02 17:13 UTC by mrkamin

What does this PR do?
This PR is raised to submit for code review in the Microvers dashboard of Mohammad Rafi Amin.

Description of the task to be completed 👎

I will be building my "BookStore" website for more than a whole week. below are the tasks that will be done.

Project 1: Initialize the project with components (React only).
Project 2: Add reducers and actions.
Project 3: Use Redux in React components.
Project 4: Connect to API.
**Project 5: Styling.**

2023-03-02 17:24 UTC, huseyinbiyik commented
Hi @mrkamin,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

⚠️ Kindly remove the instructions aiming to inform you below on your README file.
<img width="751" alt="Screenshot 2023-03-02 at 8 22 59 PM" src="https://user-images.githubusercontent.com/25887253/222504715-5aecdaf5-456e-4aad-b007-f620457d87ba.png">
<img width="751" alt="Screenshot 2023-03-02 at 8 23 04 PM" src="https://user-images.githubusercontent.com/25887253/222504720-a56b96e3-3cdf-4fd3-822b-19a19b64d432.png">


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-02 17:32 UTC, mrkamin commented
> Hi @mrkamin,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ![Alt Text](https://camo.githubusercontent.com/999c41ff216bced575a5c7873c1c4ed04ef945c867ca87788003794670ee5aa7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f785550476377453343556b586c766f6e75672f67697068792e676966) [ ](https://camo.githubusercontent.com/999c41ff216bced575a5c7873c1c4ed04ef945c867ca87788003794670ee5aa7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f785550476377453343556b586c766f6e75672f67697068792e676966) ![Alt Text](https://camo.githubusercontent.com/999c41ff216bced575a5c7873c1c4ed04ef945c867ca87788003794670ee5aa7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f785550476377453343556b586c766f6e75672f67697068792e676966) [ ](https://camo.githubusercontent.com/999c41ff216bced575a5c7873c1c4ed04ef945c867ca87788003794670ee5aa7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f785550476377453343556b586c766f6e75672f67697068792e676966)
> 
> ## Invalid Code Review Request
> ⚠️ Kindly remove the instructions aiming to inform you below on your README file. <img alt="Screenshot 2023-03-02 at 8 22 59 PM" width="751" src="https://user-images.githubusercontent.com/25887253/222504715-5aecdaf5-456e-4aad-b007-f620457d87ba.png"> <img alt="Screenshot 2023-03-02 at 8 23 04 PM" width="751" src="https://user-images.githubusercontent.com/25887253/222504720-a56b96e3-3cdf-4fd3-822b-19a19b64d432.png">
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Hi, @huseyinbiyik 
thanks for your valuable feedback

2023-03-02 18:06 UTC, huseyinbiyik requested changes
Hi @mrkamin,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Linter set up well and checks pass 🟢
- Gitflow followed 👌
- .gitignore used to ignore requested files 📁
- PR description is descriptive 📝

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 18:06 UTC, huseyinbiyik commented on src/App.css
> +  /*  padding: 0 1.3rem; */
Please don't leave any uncommented code in your codebase. In this way, you can keep your codebase neat and professional.

2023-03-02 18:06 UTC, huseyinbiyik commented on src/App.css
> +  display: flex;
Kindly DRY your CSS as mentioned [here](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md). For example, Display flex repeating in different classes for many times. Kindly use it as class attribute.

2023-03-02 18:06 UTC, huseyinbiyik commented on src/Components/NavBar.css
> +.nav {
You implemented the general layout very well 👍 But for this project, the project needs to look exactly same on the Zeplin file. Currenly almost each element on your page has a different styling from the Zeplin. To fix it, you can use the attributes provided by Zeplin to match the design. 
![Screen Recording 2023-03-02 at 8 53 05 PM](https://user-images.githubusercontent.com/25887253/222512463-cab25ec2-d606-48e1-a8cb-4b67ead79d7b.gif)

2023-03-02 20:15 UTC, mrkamin commented
> Hi @mrkamin,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! ![Almost there](https://camo.githubusercontent.com/edbd1e3e6d39b97475267aaea49f37d1576a9b49fe744fad786303284a0001ac/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f5276364747614e725262744e436f6e6c596f2f67697068792e676966) [ ](https://camo.githubusercontent.com/edbd1e3e6d39b97475267aaea49f37d1576a9b49fe744fad786303284a0001ac/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f5276364747614e725262744e436f6e6c596f2f67697068792e676966) ![Almost there](https://camo.githubusercontent.com/edbd1e3e6d39b97475267aaea49f37d1576a9b49fe744fad786303284a0001ac/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f5276364747614e725262744e436f6e6c596f2f67697068792e676966) [ ](https://camo.githubusercontent.com/edbd1e3e6d39b97475267aaea49f37d1576a9b49fe744fad786303284a0001ac/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f5276364747614e725262744e436f6e6c596f2f67697068792e676966)
> 
> ## Highlights
> * Linter set up well and checks pass 🟢
> * Gitflow followed 👌
> * .gitignore used to ignore requested files 📁
> * PR description is descriptive 📝
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> * Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example,
>   👌"Add logo to navigation bar"
>   👌"Fix close button functionality on mobile navbar"
>   ❌ "Added logo to navigation bar"
>   ❌ "Added HTML"
>   _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hi, @huseyinbiyik 
thanks for your valuable feedback I will take them into account in my future commit s

2023-03-02 20:15 UTC, mrkamin commented on src/App.css
> +  /*  padding: 0 1.3rem; */
Hi, @huseyinbiyik 
thanks for your valuable feedback

2023-03-02 20:17 UTC, mrkamin commented on src/App.css
> +  display: flex;
> Kindly DRY your CSS as mentioned [here](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md). For example, Display flex repeating in different classes for many times. Kindly use it as class attribute.

Hi, @huseyinbiyik 
thanks for your valuable feedback, could you please tell me more details how can I make it Dry as I think it is not possible.

2023-03-02 21:18 UTC, mrkamin commented on src/Components/NavBar.css
> +.nav {
Hi, @huseyinbiyik 
thanks for your valuable feedback

2023-03-02 22:01 UTC, Ismailco requested changes
### Hi @mrkamin, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-02 22:01 UTC, Ismailco commented on src/App.css
> +  display: flex;
- [ ] As the previous reviewer mentioned kindly follow DRY practices in your code, which means you shouldn't use the same property too many times, for example, you can create a class `.flex` and add `display: flex` and add the class name to your HTML class property instead. this way you can use that class name for all similar situations (for example flex)

2023-03-03 07:40 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @mrkamin 

Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- design well followed
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-03 07:56 UTC, mrkamin commented on src/App.css
> +  display: flex;
Hi, @Ismailco 
thanks for your valuable feedback

2023-03-24 20:30 UTC, merged